Documents/GitHub/Vac/Vacation-Travel Site/Models/Classes/About.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vacation_Travel_Site.Models.Classes
{
    public class About
    {
        [Key]
        public int Id { get; set; }
        public string PhotoUrl { get; set; }
        public string Desctiption { get; set; }
    }
}

Documents/GitHub/Vac/Vacation-Travel Site/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vacation_Travel_Site.Models.Classes;

namespace Vacation_Travel_Site.Controllers
{
    public class AboutController : Controller
    {
        Context context = new Context();
        // GET: About
        public ActionResult Index()
        {
            var variables = context.Abouts.ToList();
            return View(variables);
        }
    }
}

Documents/GitHub/Vac/Vacation-Travel Site/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vacation_Travel_Site.Models.Classes;

namespace Vacation_Travel_Site.Controllers
{
    public class DefaultController : Controller
    {
        Context context = new Context();
        // GET: Default
        public ActionResult Index()
        {
            var blogs = context.Blogs.Take(10).ToList();
            return View(blogs);
        }

        public ActionResult About()
        {
            return View();
        }

        public PartialViewResult PartialBlog()
        {

            var blogs = context.Blogs.OrderByDescending(b => b.Id).Take(2).ToList();
            return PartialView(blogs);
        }

        public PartialViewResult PartialTopTenBlog()
        {
            var blogs = context.Blogs.ToList();
            return PartialView(blogs);
        }

        public PartialViewResult PartialBestBlogs()
        {
            var blogs = context.Blogs.Take(3).ToList();
            return PartialView(blogs);
        }

        public PartialViewResult PartialRightBestBlogs()
        {
            var blogs = context.Blogs.Take(3).OrderByDescending(b => b.Id).ToList();
            return PartialView(blogs);
        }

        //public PartialViewResult RightPartialBlog()
        //{
        //    var blogs = context.Blogs.Where(b=>b.Id==1)
        //    return PartialView();
        //}
    }
}

Documents/GitHub/Vac/Vacation-Travel Site/Views/Default/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Free Easy-Trip Website Template | About :: w3layouts</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="~/web/css/style.css" type="text/css" media="all" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/web/css/slider.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
    <div class="content">
        <div class="wrap">
            <div class="about">
                <h3>About</h3>
                <img src="~/web/images/about_banner.jpg" alt="" />
                <p>Lorem ipsum</p>
            </div>
        </div>
    </div>
</body>
</html>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Default/Index.cshtml
@using Vacation_Travel_Site.Models.Classes
@model List<Blog>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<body>
    <div class="header-banner">
        <div class="wrap">
            <div class="banner">
                <div class="indent">
                    <h2 class="indent-left margin-bot">Plan the Easy Trip</h2>
                    <div class="banner-left">
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/glass.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Restaurants</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/flight.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Flights</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/group.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Things to do</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="con-text">
                            <div class="grid1-img">
                                <img src="~/web/images/key.png" alt="">
                            </div>
                            <div class="grid1-desc">
                                <p>Vacation Rents</p>
                            </div>
                            <div class="clear"></div>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="header_bottom_right_images">

                        <div class="slider" style=" width:650px; height:365px">
                            <ul class="rslides" id="slider1">
                                @foreach (var item in Model)
                                {
                                    <li><img src="@item.BlogImage" alt="" style=" width:650px; height:365px"></li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class"content">
        <div class="wrap">
            <div class="wrapper">
                <div class="con-top">
                    <h3>Welcome to our Travel Company!</h3>
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facil</p>
                </div>

                @Html.Action("PartialBlog", "Default")

                <div class="grids">
                    <div class="box1">

                        @Html.Action("PartialTopTenBlog", "Default")


                        @Html.Action("PartialBestBlogs", "Default")

                        @Html.Action("PartialRightBestBlogs", "Default")

                        <div class="clear"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Default/PartialBestBlogs.cshtml
@using Vacation_Travel_Site.Models.Classes
@model List<Blog>

<div class="padding1">
    <h4>Our Best Places</h4>
    <div class="box-left">
        @foreach (var item in Model)
        {
            <div class="bot-img">
                <img src="@item.BlogImage" alt="" />
            </div>
            <div class="bot-desc">
                <p>@item.Description.Substring(1,20)</p>
            </div>
            <div class="clear"></div>
        }
    </div>
</div>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Default/PartialBlog.cshtml
@using Vacation_Travel_Site.Models.Classes
@model List<Blog>

<div class="con-bot">
    @foreach (var item in Model)
    {
        <div class="left">
            <div class="bot-left">
                <img src="@item.BlogImage" alt="" />
            </div>
            <div class="left-text">
                <h4>@item.Title</h4>
                <span class="doller">@item.Date.ToString("dd.MM.yyyy")</span>
                <p>@item.Description.Substring(0,50)</p>
                <p><a href="/Blog/Detail/@item.Id"><span class="read">Read More</span></a></p>
            </div>
        </div>
    }
    
  
    <div class="clear"></div>
</div>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Default/PartialRightBestBlogs.cshtml
@using Vacation_Travel_Site.Models.Classes
@model List<Blog>

<div class="box1-left">
    @foreach (var item in Model)
    {
        <div class="bot-img">
            <img src="~/web/images/@item.BlogImage" alt="" />
        </div>
        <div class="bot-desc1">
            @*<p>@item.Description.Substring(1,100)... </p>*@
        </div>
        <div class="clear"></div>
    }

</div>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Default/PartialTopTenBlog.cshtml
@using Vacation_Travel_Site.Models.Classes
@model List<Blog>
<div class="padding">
    <h4>This Week's Top 10</h4>

    <ul class="list list-pad">
        @{ int i = 0; }
        @foreach (var item in Model)
        {
            <li class="list-bg"><span>@{i++;} @i</span><a href="/Blog/Detail/@item.Id">@item.Title</a></li>
        }


    </ul>
    <a href="#" class="link1">See all hotels</a>
</div>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Default/RightPartialBlog.cshtml
<div class="right">
        <div class="bot-left">
            <img src="~/web/images/pic2.jpg" alt="" />
        </div>
        <div class="left-text">

            <h4>Lorem ipsum dolor sit amet, conte adipiscing elit dolor sit amet</h4>
            <span class="doller">$924.99</span>
            <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismo</p>
            <p><a href="#"><span class="read">Read More >></span></a></p>
        </div>
    </div>