Documents/GitHub/Vac/Vacation-Travel Site/Models/Classes/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Vacation_Travel_Site.Models.Classes
{
    public class Blog
    {
        [Key]
        public int Id { get; set; }
        public string Title { get; set; }
        public DateTime Date { get; set; }
        public string Description { get; set; }
        public string BlogImage { get; set; }
        public ICollection<Comments> Comments{ get; set; }
    }
}

Documents/GitHub/Vac/Vacation-Travel Site/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vacation_Travel_Site.Models.Classes;

namespace Vacation_Travel_Site.Controllers
{
    public class BlogController : Controller
    {
        Context context = new Context();
        BlogComment blogComment = new BlogComment();
        // GET: Blog
        public ActionResult Index()
        {
            //var blogs = context.Blogs.ToList();

            blogComment.Blogs = context.Blogs.ToList();

            var lastBlogs = blogComment.Blogs.OrderByDescending(b=>b.Id).Take(3).ToList();
            ViewBag.lastBlogs = lastBlogs;

            return View(blogComment);
        }

        
        public ActionResult Detail(int? id)
        {
            blogComment.Blogs = context.Blogs.Where(b => b.Id == id).ToList();
            blogComment.Comments = context.Comments.Where(c => c.BlogId == id); 
            //var blog = context.Blogs.Where(b => b.Id == id).ToList();
            return View(blogComment);
        }

        [HttpGet]
        public ActionResult CreateComment(int id)
        {
            ViewBag.blogId = id;
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult CreateComment(Comments comment)
        {
            context.Comments.Add(comment);
            context.SaveChanges();

            return PartialView();
        }
    }
}

Documents/GitHub/Vac/Vacation-Travel Site/Views/Blog/CreateComment.cshtml
<div class="content-form">
    <h3>Leave a comment</h3>
    <form method="post">
        <input type="hidden" name="blogId" value="@ViewBag.blogId" required />
        <input type="text" placeholder="Name" name="Username" required />
        <input type="text" placeholder="Email" name="Email" required />
        <textarea placeholder="Message" name="Comment"></textarea>
        <input type="submit" value="SEND" />
    </form>
</div>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Blog/Detail.cshtml
@using Vacation_Travel_Site.Models.Classes
@model  BlogComment
<!DOCTYPE HTML>
<html>
<head>
    <title>Personal Blog a Blogging Category Flat Bootstarp  Responsive Website Template | Single :: w3layouts</title>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!--end slider -->
    <!--script-->
    <script type="text/javascript" src="~/web2/js/move-top.js"></script>
    <script type="text/javascript" src="~/web2/js/easing.js"></script>
    <!--/script-->


</head>
<body>

    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                <div class="single-grid">
                    @foreach (var item in Model.Blogs)
                    {
                        <img src="@item.BlogImage" alt="" style="margin-bottom: 20px" />
                        <h2>@item.Title</h2>
                        <p>
                            @item.Description
                        </p>
                    }
                </div>
                @foreach (var item in Model.Comments)
                {
                    <ul class="comment-list">
                        <li>
                            <img src="~/web2/images/avatar.png" class="img-responsive" alt="">
                            <div class="desc">
                                <p>@item.Username: @item.Comment</p>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                    </ul>
                }
               @Html.Action("CreateComment","Blog")
            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>RECENT POSTS</h3>
                    <ul>
                        <li><a href="#">Aliquam tincidunt mauris</a></li>
                        <li><a href="#">Vestibulum auctor dapibus  lipsum</a></li>
                        <li><a href="#">Nunc dignissim risus consecu</a></li>
                        <li><a href="#">Cras ornare tristiqu</a></li>
                    </ul>
                </div>
                <div class="comments">
                    <h3>RECENT COMMENTS</h3>
                    <ul>
                        <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                        <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                        <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                    </ul>
                </div>
                <div class="clearfix"></div>


                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

</body>
</html>
<!---->
<div class="footer">
    <div class="container">
        <p>Copyrights © 2015 Blog All rights reserved | Template by <a href="http://w3layouts.com/">W3layouts</a></p>
    </div>
</div>

Documents/GitHub/Vac/Vacation-Travel Site/Views/Blog/Index.cshtml
@using Vacation_Travel_Site.Models.Classes
@model  BlogComment
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>

    <link href="/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
</head>
<body>
    <!---header---->
    <div class="header">
        <div class="container">


            <div class="clearfix"></div>

        </div>
    </div>
    <!--/header-->

    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">

                @foreach (var blog in Model.Blogs)
                {
                    <div class="single-grid">
                        <img src="@blog.BlogImage" alt="" />
                        <a href="/Blog/Detail/@blog.Id">@blog.Title</a>
                        <p>@blog.Description</p>
                    </div>
                    <br /><br />
                }






                <ul class="comment-list">
                    <h5 class="post-author_head">Written by <a href="#" title="Posts by admin" rel="author">admin</a></h5>
                    <li>
                        <img src="/web2/images/avatar.png" class="img-responsive" alt="">
                        <div class="desc">
                            <p>View all posts by: <a href="#" title="Posts by admin" rel="author">admin</a></p>
                        </div>
                        <div class="clearfix"></div>
                    </li>
                </ul>
            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>RECENT POSTS</h3>
                    @foreach (var item in ViewBag.lastBlogs)
                    {
                        <ul>
                            <li><a href="/Blog/Detail/@item.Id">@item.Title</a></li>
                        </ul>
                    }

                </div>
                <div class="comments">
                    <h3>RECENT COMMENTS</h3>
                    <ul>
                        <li><a href="#">Amada Doe </a> on <a href="#">Hello World!</a></li>
                        <li><a href="#">Peter Doe </a> on <a href="#"> Photography</a></li>
                        <li><a href="#">Steve Roberts  </a> on <a href="#">HTML5/CSS3</a></li>
                    </ul>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>